# config/auditor/static/auditor.yaml

path_to_auditor: "model_checkpoints/auditor/auditor.pkl"
path_to_model: "model_checkpoints/auditor/model.pkl"
model_plugin:
  name: "pategan"
  params: {"batch_size": 128, "n_iter": 1000}

trust_dimensions:
  fidelity_evaluators:
    - "JSD"
    - "Wasserstein Distance"
    - "MMD"
    - "KL-Divergence"
    - "MMDAgg-test"
    - "precision_recall"
  privacy_evaluators:
    - "epsilon-identifiability"
    - "Attribute Disclosure Risk"
  weights:
    privacy: 0.5
    fidelity: 0.5

optional_params:
  reference_size: 10

fractions: [0, 0.1, 0.15, 0.156, 0.159, 0.5, 0.61, 0.73, 0.8, 0.81, 1]
